version: '3'
services:
  mole-mock:
    image: node:alpine
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3002:3000
    command: npm run start:dev
    depends_on:
      - database

  database:
    image: postgres:alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mockingbird
      - POSTGRES_USER=mockingbird
      - POSTGRES_DB=mockingbird
