const env = process.env || {};

export default {
  PORT: env.PORT,
  DATABASE_URL: env.DATABASE_URL,
  RECAPTCHA_KEY: env.RECAPTCHA_KEY,
  RECAPTCHA_URL: env.RECAPTCHA_URL,
  JWT_TIME_EXPIRE: env.JWT_TIME_EXPIRE,
  JWT_SECRET_KEY: env.JWT_SECRET_KEY,
};
